development:
  title:     '2017 Southeast Interscholastic Championships'
  hotfolder: .\results
  max_time:  180

test:
  title:     '2017 Southeast Interscholastic Championships'
  hotfolder: .\results
  max_time:  180

