development:
  title:     '2019 Southeast Interscholastic Championships'
  hotfolder: ./results
  max_time:  180

test:
  title:     '2019 Southeast Interscholastic Championships'
  hotfolder: ./results
  max_time:  180

